url: https://L0rD59.github.io/K1164
baseurl:

exclude:
  - docker/
  - Makefile
  - README.md

# Site settings
title: "ROK : Kingdom 1164"
email: K1164@gmail.com
description: "Rise Of Kingdoms: Kingdom 1164, a peaceful land waiting for war... ! "

# Header
intro:
  lead-in : ""
  heading : ""


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/riseofkingdoms?lang=fr
  - title: facebook
    url: https://www.facebook.com/riseofkingdomsgame/

# Build settings
markdown: kramdown
permalink: pretty
